import 'package:json_annotation/json_annotation.dart';
import 'package:tradeverse/features/chat/domain/entity/message.dart';
import 'package:tradeverse/features/chat/domain/entity/user.dart';
import 'user_api_model.dart'; // Changed import to use UserApiModel from the chat feature

part 'message_api_model.g.dart'; // This file will be generated by build_runner

// Helper functions for User <-> UserApiModel conversion
User _userFromJson(Map<String, dynamic> json) => UserApiModel.fromJson(json);
Map<String, dynamic> _userToJson(User user) => (user as UserApiModel).toJson();

User? _nullableUserFromJson(Map<String, dynamic>? json) =>
    json == null ? null : UserApiModel.fromJson(json);
Map<String, dynamic>? _nullableUserToJson(User? user) =>
    user == null ? null : (user as UserApiModel).toJson();

@JsonSerializable()
class MessageApiModel extends Message {
  // Renamed to MessageApiModel
  @JsonKey(name: '_id')
  final String idModel;
  @JsonKey(name: 'conversationId')
  final String conversationIdModel;

  @JsonKey(
    name: 'sender',
    fromJson: _userFromJson, // Use custom fromJson
    toJson: _userToJson, // Use custom toJson
  )
  final User senderModel; // Type remains User for domain entity consistency

  @JsonKey(
    name: 'recipient',
    fromJson: _nullableUserFromJson, // Use custom fromJson for nullable
    toJson: _nullableUserToJson, // Use custom toJson for nullable
  )
  final User? recipientModel; // Type remains User? for domain entity consistency

  @JsonKey(name: 'text')
  final String? textModel;
  @JsonKey(name: 'file')
  final String? fileModel;
  @JsonKey(name: 'createdAt')
  final DateTime createdAtModel;
  @JsonKey(name: 'tempId') // Map 'tempId' from JSON
  final String? tempIdModel;

  const MessageApiModel({
    required this.idModel,
    required this.conversationIdModel,
    required this.senderModel,
    this.recipientModel,
    this.textModel,
    this.fileModel,
    required this.createdAtModel,
    this.tempIdModel,
  }) : super(
         id: idModel,
         conversationId: conversationIdModel,
         sender: senderModel,
         recipient: recipientModel,
         text: textModel,
         file: fileModel,
         createdAt: createdAtModel,
       );

  factory MessageApiModel.fromJson(Map<String, dynamic> json) =>
      _$MessageApiModelFromJson(json);

  Map<String, dynamic> toJson() => _$MessageApiModelToJson(this);
}
